import type { Food, FoodUnit, UnitKind } from './types'

/**
 * The built-in food database: common Greek staples and gym basics, per 100 g.
 * Values are standard reference values (USDA FoodData Central and typical Greek product labels), rounded.
 * Names say "cooked" or "raw/dry" wherever the difference matters (rice, pasta, meat, legumes, potatoes).
 * Ids are stored inside meal plans: add foods freely, but never rename or remove an id.
 */

type M = [kcal: number, protein: number, carbs: number, fat: number]

const u = (kind: UnitKind, g: number): FoodUnit => ({ kind, g })

function f(id: string, en: string, el: string, m: M, extra: { aliases?: string[]; unit?: FoodUnit } = {}): Food {
  const [kcal, protein, carbs, fat] = m
  return { id, en, el, kcal, protein, carbs, fat, ...extra }
}

export const FOODS: Food[] = [
  /* ---------------------------------------------------------------- dairy and eggs */
  f('greek-yogurt-2', 'Greek yogurt 2%', 'Γιαούρτι στραγγιστό 2%', [73, 9.9, 3, 2], { aliases: ['strained yoghurt', 'fage', 'giaourti', 'yoghurt'] }),
  f('greek-yogurt-0', 'Greek yogurt 0%', 'Γιαούρτι στραγγιστό 0%', [54, 10.3, 3, 0], { aliases: ['fat free yogurt', 'fage 0', 'giaourti', 'yoghurt'] }),
  f('greek-yogurt-5', 'Greek yogurt 5%', 'Γιαούρτι στραγγιστό 5%', [93, 9, 3, 5], { aliases: ['full fat yogurt', 'giaourti', 'yoghurt'] }),
  f('yogurt-plain', 'Plain yogurt, whole milk', 'Γιαούρτι αγελαδινό πλήρες', [61, 3.5, 4.7, 3.3], { aliases: ['giaourti', 'yoghurt'] }),
  f('kefir', 'Kefir, low fat', 'Κεφίρ light', [41, 3.8, 4.5, 0.9], { aliases: ['kefir'] }),
  f('feta', 'Feta cheese', 'Φέτα', [264, 14.2, 4.1, 21.3], { aliases: ['feta', 'cheese', 'tyri'] }),
  f('feta-light', 'Feta, light', 'Φέτα light', [175, 17, 1.5, 11], { aliases: ['feta', 'low fat feta', 'tyri'] }),
  f('graviera', 'Graviera cheese', 'Γραβιέρα', [395, 26, 0.5, 32], { aliases: ['graviera', 'gruyere', 'cheese', 'tyri'] }),
  f('kasseri', 'Kasseri cheese', 'Κασέρι', [370, 24, 1.5, 30], { aliases: ['kaseri', 'kasseri', 'cheese', 'tyri'] }),
  f('kefalotyri', 'Kefalotyri cheese', 'Κεφαλοτύρι', [392, 27, 1, 31], { aliases: ['kefalotiri', 'cheese', 'tyri'] }),
  f('halloumi', 'Halloumi', 'Χαλούμι', [321, 21, 2, 25], { aliases: ['haloumi', 'cheese', 'tyri'] }),
  f('mozzarella-light', 'Mozzarella, part skim', 'Μοτσαρέλα light', [254, 24.3, 2.8, 15.9], { aliases: ['mozarella', 'cheese', 'tyri'] }),
  f('gouda', 'Gouda', 'Γκούντα', [356, 24.9, 2.2, 27.4], { aliases: ['gouda', 'cheese slice', 'tyri'], unit: u('slice', 20) }),
  f('gouda-light', 'Gouda, light (slices)', 'Γκούντα light (φέτες)', [270, 30, 0.5, 16.5], { aliases: ['light cheese', 'tyri'], unit: u('slice', 20) }),
  f('cheddar', 'Cheddar', 'Τσένταρ', [403, 22.9, 3.1, 33.3], { aliases: ['cheese', 'tyri'] }),
  f('parmesan', 'Parmesan', 'Παρμεζάνα', [392, 35.8, 3.2, 25.8], { aliases: ['parmigiano', 'cheese', 'tyri'] }),
  f('cottage-2', 'Cottage cheese, low fat', 'Τυρί cottage light', [81, 10.5, 4.8, 2.3], { aliases: ['cottage', 'kotaz'] }),
  f('cottage-full', 'Cottage cheese, full fat', 'Τυρί cottage πλήρες', [98, 11.1, 3.4, 4.3], { aliases: ['cottage', 'kotaz'] }),
  f('anthotyro', 'Anthotyro (fresh whey cheese)', 'Ανθότυρο', [175, 11, 4, 12.5], { aliases: ['anthotiro', 'mizithra', 'myzithra', 'ricotta'] }),
  f('milk-whole', 'Milk, whole 3.5%', 'Γάλα πλήρες 3,5%', [61, 3.2, 4.8, 3.3], { aliases: ['gala', 'milk full fat'] }),
  f('milk-semi', 'Milk, semi-skimmed 1.5%', 'Γάλα ελαφρύ 1,5%', [47, 3.4, 4.9, 1.5], { aliases: ['gala', 'light milk', 'milk 1.5'] }),
  f('milk-skim', 'Milk, skimmed 0%', 'Γάλα άπαχο 0%', [34, 3.4, 5, 0.1], { aliases: ['gala', 'fat free milk'] }),
  f('soy-drink', 'Soy drink, unsweetened', 'Ρόφημα σόγιας χωρίς ζάχαρη', [33, 3.3, 0.7, 1.8], { aliases: ['soy milk', 'soya', 'gala sogias'] }),
  f('almond-drink', 'Almond drink, unsweetened', 'Ρόφημα αμυγδάλου χωρίς ζάχαρη', [15, 0.6, 0.3, 1.1], { aliases: ['almond milk', 'gala amygdalou'] }),
  f('oat-drink', 'Oat drink', 'Ρόφημα βρώμης', [46, 1, 6.7, 1.5], { aliases: ['oat milk', 'gala vromis'] }),
  f('egg', 'Egg', 'Αυγό', [143, 12.6, 0.7, 9.5], { aliases: ['eggs', 'avga', 'avgo', 'boiled egg', 'vrasto'], unit: u('piece', 50) }),
  f('egg-white', 'Egg white', 'Ασπράδι αυγού', [52, 10.9, 0.7, 0.2], { aliases: ['egg whites', 'asprades', 'aspradi'], unit: u('piece', 33) }),
  f('whey', 'Whey protein powder', 'Πρωτεΐνη whey (σκόνη)', [390, 78, 7, 6], { aliases: ['protein shake', 'whey', 'proteini', 'isolate'], unit: u('scoop', 30) }),
  f('casein', 'Casein protein powder', 'Πρωτεΐνη καζεΐνη (σκόνη)', [360, 80, 6, 1.5], { aliases: ['protein', 'kazeini', 'proteini'], unit: u('scoop', 30) }),
  f('butter', 'Butter', 'Βούτυρο', [717, 0.9, 0.1, 81], { aliases: ['voutyro'], unit: u('tsp', 5) }),
  f('tzatziki', 'Tzatziki', 'Τζατζίκι', [105, 4.5, 4.5, 8], { aliases: ['tzatziki', 'tsatsiki', 'yogurt dip'] }),

  /* ---------------------------------------------------------------- meat */
  f('chicken-breast-cooked', 'Chicken breast, grilled (cooked)', 'Στήθος κοτόπουλο ψητό (μαγειρεμένο)', [165, 31, 0, 3.6], { aliases: ['kotopoulo', 'stithos', 'fileto'] }),
  f('chicken-breast-raw', 'Chicken breast, raw', 'Στήθος κοτόπουλο ωμό', [120, 22.5, 0, 2.6], { aliases: ['kotopoulo', 'stithos', 'fileto'] }),
  f('chicken-thigh-cooked', 'Chicken thigh, skinless (cooked)', 'Μπούτι κοτόπουλο χωρίς πέτσα (μαγειρεμένο)', [209, 26, 0, 10.9], { aliases: ['kotopoulo', 'bouti', 'chicken leg'] }),
  f('chicken-thigh-raw', 'Chicken thigh, skinless, raw', 'Μπούτι κοτόπουλο χωρίς πέτσα ωμό', [121, 19.7, 0, 4.1], { aliases: ['kotopoulo', 'bouti'] }),
  f('chicken-souvlaki', 'Chicken souvlaki (skewer)', 'Σουβλάκι κοτόπουλο (καλαμάκι)', [170, 27, 1, 6.5], { aliases: ['kalamaki', 'souvlaki', 'kotopoulo', 'skewer'], unit: u('skewer', 90) }),
  f('pork-souvlaki', 'Pork souvlaki (skewer)', 'Σουβλάκι χοιρινό (καλαμάκι)', [210, 27, 1, 11], { aliases: ['kalamaki', 'souvlaki', 'xoirino', 'choirino', 'skewer'], unit: u('skewer', 90) }),
  f('chicken-gyros', 'Chicken gyros (meat only)', 'Γύρος κοτόπουλο (σκέτος)', [210, 21, 3, 12.5], { aliases: ['gyro', 'giros', 'yiros', 'kotopoulo'] }),
  f('pork-gyros', 'Pork gyros (meat only)', 'Γύρος χοιρινός (σκέτος)', [260, 18, 3, 19.5], { aliases: ['gyro', 'giros', 'yiros', 'xoirinos', 'choirinos'] }),
  f('gyros-pita-pork', 'Pork gyros pita wrap', 'Πίτα γύρος χοιρινός', [225, 10, 22, 10.5], { aliases: ['pita gyro', 'souvlaki pita', 'tylixto', 'tylichto', 'wrap'], unit: u('piece', 300) }),
  f('gyros-pita-chicken', 'Chicken gyros pita wrap', 'Πίτα γύρος κοτόπουλο', [200, 11, 21, 8], { aliases: ['pita gyro', 'souvlaki pita', 'tylixto', 'tylichto', 'wrap'], unit: u('piece', 300) }),
  f('pork-loin-cooked', 'Pork tenderloin, roasted', 'Χοιρινό φιλέτο ψητό', [143, 26, 0, 3.5], { aliases: ['xoirino', 'choirino', 'fileto'] }),
  f('pork-chop-cooked', 'Pork chop, grilled', 'Χοιρινή μπριζόλα ψητή', [231, 25.7, 0, 13.9], { aliases: ['brizola', 'mprizola', 'xoirini'] }),
  f('loukaniko', 'Loukaniko (Greek pork sausage)', 'Λουκάνικο χωριάτικο', [300, 15, 2, 26], { aliases: ['loukaniko', 'sausage'] }),
  f('bifteki', 'Bifteki (Greek beef patty), grilled', 'Μπιφτέκι ψητό', [240, 20, 6, 15], { aliases: ['biftekia', 'mpifteki', 'burger patty'], unit: u('piece', 120) }),
  f('keftedes', 'Keftedes (fried meatballs)', 'Κεφτέδες τηγανητοί', [270, 16, 10, 18.5], { aliases: ['keftedakia', 'meatballs'], unit: u('piece', 30) }),
  f('beef-mince-5-raw', 'Beef mince 5% fat, raw', 'Κιμάς μοσχαρίσιος 5%, ωμός', [137, 21.4, 0, 5], { aliases: ['kimas', 'ground beef', 'lean mince'] }),
  f('beef-mince-5-cooked', 'Beef mince 5% fat, cooked', 'Κιμάς μοσχαρίσιος 5%, μαγειρεμένος', [164, 25.4, 0, 6.4], { aliases: ['kimas', 'ground beef', 'lean mince'] }),
  f('beef-mince-15-raw', 'Beef mince 15% fat, raw', 'Κιμάς μοσχαρίσιος 15%, ωμός', [215, 18.6, 0, 15], { aliases: ['kimas', 'ground beef'] }),
  f('beef-steak-cooked', 'Beef steak, lean, grilled', 'Μοσχαρίσια μπριζόλα άπαχη ψητή', [186, 29, 0, 7.3], { aliases: ['moschari', 'mosxari', 'sirloin', 'brizola'] }),
  f('beef-stew', 'Beef stewed in tomato (kokkinisto)', 'Μοσχάρι κοκκινιστό', [165, 20, 3, 8], { aliases: ['kokkinisto', 'moschari', 'mosxari'] }),
  f('lamb-leg-cooked', 'Lamb leg, roasted', 'Αρνί μπούτι ψητό', [191, 28.3, 0, 7.7], { aliases: ['arni', 'lamb'] }),
  f('lamb-chops', 'Lamb chops (paidakia), grilled', 'Παϊδάκια αρνίσια ψητά', [294, 25, 0, 21], { aliases: ['paidakia', 'arni'] }),
  f('turkey-breast-cooked', 'Turkey breast, roasted', 'Στήθος γαλοπούλας ψητό', [135, 30, 0, 1.5], { aliases: ['galopoula', 'turkey'] }),
  f('turkey-slices', 'Turkey breast slices (deli)', 'Γαλοπούλα φέτες', [100, 17, 3, 2], { aliases: ['galopoula', 'deli', 'cold cuts', 'allantiko'], unit: u('slice', 20) }),
  f('ham-lean', 'Ham, lean (deli)', 'Ζαμπόν άπαχο', [110, 18, 1.5, 3.5], { aliases: ['zampon', 'deli', 'cold cuts'], unit: u('slice', 20) }),

  /* ---------------------------------------------------------------- fish and seafood */
  f('salmon-raw', 'Salmon, raw', 'Σολομός ωμός', [208, 20.4, 0, 13.4], { aliases: ['solomos'] }),
  f('salmon-cooked', 'Salmon, grilled (cooked)', 'Σολομός ψητός', [206, 22.1, 0, 12.4], { aliases: ['solomos'] }),
  f('tuna-water', 'Tuna in water, drained', 'Τόνος σε νερό (στραγγισμένος)', [116, 25.5, 0, 0.8], { aliases: ['tonos', 'canned tuna', 'konserva'] }),
  f('tuna-oil', 'Tuna in oil, drained', 'Τόνος σε λάδι (στραγγισμένος)', [198, 29.1, 0, 8.2], { aliases: ['tonos', 'canned tuna', 'konserva'] }),
  f('sea-bream', 'Sea bream (tsipoura), grilled', 'Τσιπούρα ψητή', [145, 24, 0, 5.5], { aliases: ['tsipoura', 'dorade', 'fish', 'psari'] }),
  f('sea-bass', 'Sea bass (lavraki), grilled', 'Λαβράκι ψητό', [124, 23.6, 0, 2.6], { aliases: ['lavraki', 'branzino', 'fish', 'psari'] }),
  f('cod-cooked', 'Cod, baked', 'Μπακαλιάρος ψητός', [105, 22.8, 0, 0.9], { aliases: ['bakaliaros', 'mpakaliaros', 'fish', 'psari'] }),
  f('mackerel', 'Mackerel, grilled', 'Σκουμπρί ψητό', [262, 23.9, 0, 17.8], { aliases: ['skoumpri', 'fish', 'psari'] }),
  f('sardines-oil', 'Sardines in oil, drained', 'Σαρδέλες σε λάδι', [208, 24.6, 0, 11.5], { aliases: ['sardeles', 'fish'] }),
  f('shrimp', 'Shrimp, cooked', 'Γαρίδες μαγειρεμένες', [99, 24, 0.2, 0.3], { aliases: ['garides', 'prawns'] }),
  f('octopus', 'Octopus, cooked', 'Χταπόδι μαγειρεμένο', [164, 29.8, 4.4, 2.1], { aliases: ['chtapodi', 'xtapodi'] }),
  f('squid-grilled', 'Squid (kalamari), grilled', 'Καλαμάρι ψητό', [105, 18, 3, 2], { aliases: ['kalamari', 'calamari'] }),

  /* ---------------------------------------------------------------- grains, bread, potatoes */
  f('oats', 'Oats, rolled (dry)', 'Βρώμη νιφάδες', [379, 13.2, 67.7, 6.5], { aliases: ['oatmeal', 'porridge', 'vromi', 'bromi'] }),
  f('rice-white-cooked', 'Rice, white, cooked', 'Ρύζι λευκό βρασμένο', [130, 2.7, 28.2, 0.3], { aliases: ['ryzi', 'rizi', 'basmati', 'jasmine'] }),
  f('rice-white-raw', 'Rice, white, raw (dry)', 'Ρύζι λευκό ωμό', [360, 6.6, 79.3, 0.6], { aliases: ['ryzi', 'rizi', 'basmati'] }),
  f('rice-brown-cooked', 'Rice, brown, cooked', 'Ρύζι καστανό βρασμένο', [123, 2.7, 25.6, 1], { aliases: ['ryzi', 'rizi', 'wholegrain rice'] }),
  f('rice-brown-raw', 'Rice, brown, raw (dry)', 'Ρύζι καστανό ωμό', [367, 7.5, 76.2, 3.2], { aliases: ['ryzi', 'rizi'] }),
  f('pasta-cooked', 'Pasta, cooked', 'Ζυμαρικά βρασμένα', [158, 5.8, 30.9, 0.9], { aliases: ['spaghetti', 'makaronia', 'penne', 'zymarika'] }),
  f('pasta-raw', 'Pasta, raw (dry)', 'Ζυμαρικά ωμά', [371, 13, 74.7, 1.5], { aliases: ['spaghetti', 'makaronia', 'penne', 'zymarika'] }),
  f('pasta-wholewheat-cooked', 'Wholewheat pasta, cooked', 'Ζυμαρικά ολικής άλεσης βρασμένα', [149, 6, 30, 1.7], { aliases: ['spaghetti', 'makaronia', 'olikis'] }),
  f('orzo-cooked', 'Orzo (kritharaki), cooked', 'Κριθαράκι βρασμένο', [158, 5.8, 30.9, 0.9], { aliases: ['kritharaki', 'manestra', 'giouvetsi'] }),
  f('orzo-raw', 'Orzo (kritharaki), raw (dry)', 'Κριθαράκι ωμό', [357, 12.5, 72, 1.5], { aliases: ['kritharaki', 'manestra'] }),
  f('trahanas', 'Trahanas (dry)', 'Τραχανάς', [355, 13, 68, 3.5], { aliases: ['trahana', 'trachanas', 'xinochondros'] }),
  f('couscous-cooked', 'Couscous, cooked', 'Κουσκούς βρασμένο', [112, 3.8, 23.2, 0.2], { aliases: ['kouskous'] }),
  f('bulgur-cooked', 'Bulgur, cooked', 'Πλιγούρι βρασμένο', [83, 3.1, 18.6, 0.2], { aliases: ['pligouri', 'bulghur'] }),
  f('quinoa-cooked', 'Quinoa, cooked', 'Κινόα βρασμένη', [120, 4.4, 21.3, 1.9], { aliases: ['kinoa'] }),
  f('potato-boiled', 'Potatoes, boiled', 'Πατάτες βραστές', [86, 1.7, 20, 0.1], { aliases: ['patates', 'patata'] }),
  f('potato-baked', 'Potato, baked with skin', 'Πατάτα ψητή με τη φλούδα', [93, 2.5, 21.2, 0.1], { aliases: ['patates', 'patata', 'jacket potato'] }),
  f('potato-raw', 'Potatoes, raw', 'Πατάτες ωμές', [77, 2, 17.5, 0.1], { aliases: ['patates', 'patata'] }),
  f('potatoes-oven-greek', 'Oven potatoes with olive oil (lemon potatoes)', 'Πατάτες φούρνου λεμονάτες', [150, 2, 20, 7], { aliases: ['patates fournou', 'lemonates', 'roast potatoes'] }),
  f('fries', 'French fries', 'Πατάτες τηγανητές', [312, 3.4, 41, 15], { aliases: ['patates tiganites', 'chips'] }),
  f('sweet-potato-baked', 'Sweet potato, baked', 'Γλυκοπατάτα ψητή', [90, 2, 20.7, 0.2], { aliases: ['glykopatata', 'glikopatata'] }),
  f('sweet-potato-raw', 'Sweet potato, raw', 'Γλυκοπατάτα ωμή', [86, 1.6, 20.1, 0.1], { aliases: ['glykopatata', 'glikopatata'] }),
  f('bread-white', 'Bread, white (sliced / toast)', 'Ψωμί λευκό (τοστ)', [265, 9, 49, 3.2], { aliases: ['psomi', 'tost', 'toast'], unit: u('slice', 30) }),
  f('bread-wholegrain', 'Bread, wholegrain', 'Ψωμί ολικής άλεσης', [247, 13, 41, 3.4], { aliases: ['psomi', 'olikis', 'wholemeal', 'brown bread'], unit: u('slice', 30) }),
  f('bread-village', 'Village bread (horiatiko)', 'Ψωμί χωριάτικο', [260, 8.5, 50, 2.5], { aliases: ['psomi', 'choriatiko', 'xoriatiko', 'sourdough'], unit: u('slice', 40) }),
  f('bread-rye', 'Rye bread', 'Ψωμί σίκαλης', [259, 8.5, 48.3, 3.3], { aliases: ['psomi', 'sikali'], unit: u('slice', 30) }),
  f('pita-souvlaki', 'Pita bread (for souvlaki)', 'Πίτα για σουβλάκι', [285, 8, 50, 5.5], { aliases: ['pita', 'pitta', 'arabiki'], unit: u('piece', 70) }),
  f('pita-pocket', 'Pita pocket (Arabic)', 'Αραβική πίτα', [275, 9.1, 55.7, 1.2], { aliases: ['pita', 'pitta', 'arabiki'], unit: u('piece', 60) }),
  f('tortilla', 'Tortilla wrap', 'Τορτίγια', [310, 8.3, 51.6, 7.7], { aliases: ['wrap', 'tortigia'], unit: u('piece', 60) }),
  f('rusk-barley', 'Barley rusk (paximadi)', 'Παξιμάδι κρίθινο', [360, 11, 70, 3.2], { aliases: ['paximadi', 'dakos', 'krithino', 'rusks'], unit: u('piece', 30) }),
  f('friganies', 'Toasted bread slices (friganies)', 'Φρυγανιές', [400, 12, 72, 6], { aliases: ['friganies', 'fryganies', 'crispbread', 'rusks'], unit: u('slice', 10) }),
  f('koulouri', 'Koulouri (sesame bread ring)', 'Κουλούρι Θεσσαλονίκης', [330, 10.5, 56, 7], { aliases: ['koulouri', 'simit'], unit: u('piece', 90) }),
  f('rice-cakes', 'Rice cakes', 'Ρυζογκοφρέτες', [387, 8.2, 81.5, 2.8], { aliases: ['ryzogkofretes', 'rice crackers'], unit: u('piece', 9) }),
  f('cornflakes', 'Cornflakes', 'Κορν φλέικς', [357, 7.5, 84, 0.4], { aliases: ['cereal', 'dimitriaka', 'corn flakes'] }),
  f('muesli', 'Muesli', 'Μούσλι', [367, 10, 66, 6], { aliases: ['cereal', 'dimitriaka', 'granola'] }),
  f('spanakopita', 'Spanakopita (spinach pie)', 'Σπανακόπιτα', [260, 7, 23, 16], { aliases: ['spanakopita', 'pie', 'pita'], unit: u('piece', 150) }),
  f('tiropita', 'Tiropita (cheese pie)', 'Τυρόπιτα', [320, 9, 25, 21], { aliases: ['tyropita', 'tiropita', 'cheese pie', 'pita'], unit: u('piece', 150) }),

  /* ---------------------------------------------------------------- legumes and Greek dishes */
  f('white-beans-cooked', 'White beans, boiled', 'Φασόλια μέτρια βρασμένα', [140, 8.2, 26.1, 0.6], { aliases: ['fasolia', 'navy beans', 'cannellini'] }),
  f('white-beans-dry', 'White beans, dry', 'Φασόλια ξερά', [339, 21.9, 62.4, 1.1], { aliases: ['fasolia'] }),
  f('fasolada', 'Fasolada (bean soup)', 'Φασολάδα', [118, 5.5, 14, 4.5], { aliases: ['fasolada', 'bean soup'] }),
  f('gigantes', 'Gigantes plaki (baked giant beans)', 'Γίγαντες πλακί', [150, 5.5, 15, 7.5], { aliases: ['gigantes', 'giant beans', 'butter beans'] }),
  f('lentils-cooked', 'Lentils, boiled', 'Φακές βρασμένες', [116, 9, 20.1, 0.4], { aliases: ['fakes', 'lentil'] }),
  f('lentils-dry', 'Lentils, dry', 'Φακές ξερές', [352, 24.6, 63.4, 1.1], { aliases: ['fakes'] }),
  f('fakes-soup', 'Fakes (lentil soup)', 'Φακές σούπα', [107, 6, 14, 3], { aliases: ['fakes', 'lentil soup'] }),
  f('chickpeas-cooked', 'Chickpeas, boiled', 'Ρεβίθια βρασμένα', [164, 8.9, 27.4, 2.6], { aliases: ['revithia', 'garbanzo'] }),
  f('chickpeas-dry', 'Chickpeas, dry', 'Ρεβίθια ξερά', [378, 20.5, 63, 6], { aliases: ['revithia'] }),
  f('hummus', 'Hummus', 'Χούμους', [166, 7.9, 14.3, 9.6], { aliases: ['houmous', 'humus'] }),
  f('fava', 'Fava (yellow split pea purée)', 'Φάβα', [145, 7, 18, 5], { aliases: ['fava', 'split peas'] }),
  f('kidney-beans-cooked', 'Kidney beans, boiled', 'Κόκκινα φασόλια βρασμένα', [127, 8.7, 22.8, 0.5], { aliases: ['fasolia', 'red beans'] }),
  f('peas-cooked', 'Green peas, cooked', 'Αρακάς βρασμένος', [84, 5.4, 15.6, 0.2], { aliases: ['arakas', 'peas'] }),
  f('horta', 'Horta (boiled wild greens)', 'Χόρτα βραστά', [30, 2.3, 5, 0.4], { aliases: ['horta', 'chorta', 'vlita', 'radikia', 'greens'] }),
  f('briam', 'Briam (roasted vegetables in olive oil)', 'Μπριάμ', [110, 2, 9, 7.5], { aliases: ['briam', 'mpriam', 'tourlou'] }),
  f('fasolakia', 'Fasolakia (green beans in tomato and oil)', 'Φασολάκια λαδερά', [98, 2, 8, 6.5], { aliases: ['fasolakia', 'ladera'] }),
  f('gemista', 'Gemista (stuffed tomatoes and peppers)', 'Γεμιστά', [120, 2, 16, 5.5], { aliases: ['gemista', 'yemista', 'stuffed'] }),
  f('dolmadakia', 'Dolmadakia (rice-stuffed vine leaves)', 'Ντολμαδάκια γιαλαντζί', [150, 2.5, 18, 7.5], { aliases: ['dolmades', 'ntolmadakia', 'sarmadakia'], unit: u('piece', 25) }),
  f('spanakorizo', 'Spanakorizo (spinach rice)', 'Σπανακόρυζο', [112, 3, 16, 4], { aliases: ['spanakorizo', 'spanakoryzo'] }),
  f('moussaka', 'Moussaka', 'Μουσακάς', [180, 8, 10, 12], { aliases: ['mousakas', 'moussakas'] }),
  f('pastitsio', 'Pastitsio', 'Παστίτσιο', [211, 10, 17, 11.5], { aliases: ['pastitsio', 'pasticcio'] }),
  f('horiatiki', 'Greek salad (horiatiki), with feta and oil', 'Χωριάτικη σαλάτα', [135, 3.5, 4, 12], { aliases: ['horiatiki', 'choriatiki', 'salata', 'greek salad'] }),

  /* ---------------------------------------------------------------- vegetables */
  f('tomato', 'Tomato', 'Ντομάτα', [18, 0.9, 3.9, 0.2], { aliases: ['domata', 'ntomata', 'tomatoes'], unit: u('piece', 120) }),
  f('cherry-tomatoes', 'Cherry tomatoes', 'Ντοματίνια', [18, 0.9, 3.9, 0.2], { aliases: ['ntomatinia', 'domatinia'], unit: u('piece', 15) }),
  f('cucumber', 'Cucumber', 'Αγγούρι', [15, 0.7, 3.6, 0.1], { aliases: ['angouri', 'agouri'] }),
  f('onion', 'Onion', 'Κρεμμύδι', [40, 1.1, 9.3, 0.1], { aliases: ['kremmydi', 'kremidi', 'red onion'] }),
  f('green-pepper', 'Green pepper', 'Πιπεριά πράσινη', [20, 0.9, 4.6, 0.2], { aliases: ['piperia'], unit: u('piece', 120) }),
  f('red-pepper', 'Red pepper', 'Πιπεριά κόκκινη', [31, 1, 6, 0.3], { aliases: ['piperia', 'florinis'], unit: u('piece', 120) }),
  f('lettuce', 'Lettuce (romaine)', 'Μαρούλι', [17, 1.2, 3.3, 0.3], { aliases: ['marouli', 'salad'] }),
  f('cabbage', 'Cabbage', 'Λάχανο', [25, 1.3, 5.8, 0.1], { aliases: ['lachano', 'laxano'] }),
  f('spinach', 'Spinach', 'Σπανάκι', [23, 2.9, 3.6, 0.4], { aliases: ['spanaki'] }),
  f('broccoli', 'Broccoli', 'Μπρόκολο', [34, 2.8, 6.6, 0.4], { aliases: ['brokolo', 'mprokolo'] }),
  f('cauliflower', 'Cauliflower', 'Κουνουπίδι', [25, 1.9, 5, 0.3], { aliases: ['kounoupidi'] }),
  f('zucchini', 'Zucchini (courgette)', 'Κολοκυθάκι', [17, 1.2, 3.1, 0.3], { aliases: ['kolokythakia', 'kolokithakia', 'courgette'] }),
  f('eggplant', 'Eggplant (aubergine)', 'Μελιτζάνα', [25, 1, 5.9, 0.2], { aliases: ['melitzana', 'aubergine'] }),
  f('carrot', 'Carrot', 'Καρότο', [41, 0.9, 9.6, 0.2], { aliases: ['karoto'], unit: u('piece', 70) }),
  f('green-beans', 'Green beans', 'Φασολάκια', [31, 1.8, 7, 0.2], { aliases: ['fasolakia'] }),
  f('mushrooms', 'Mushrooms', 'Μανιτάρια', [22, 3.1, 3.3, 0.3], { aliases: ['manitaria'] }),
  f('beetroot', 'Beetroot, boiled', 'Παντζάρια βραστά', [44, 1.7, 10, 0.2], { aliases: ['pantzaria', 'beets'] }),
  f('sweetcorn', 'Sweetcorn', 'Καλαμπόκι', [86, 3.3, 19, 1.4], { aliases: ['kalamboki', 'kalampoki', 'corn'] }),
  f('avocado', 'Avocado', 'Αβοκάντο', [160, 2, 8.5, 14.7], { aliases: ['avokanto'] }),
  f('olives-kalamata', 'Olives, Kalamata', 'Ελιές Καλαμών', [230, 1.5, 6, 22], { aliases: ['elies', 'olive'], unit: u('piece', 4) }),
  f('olives-green', 'Olives, green', 'Ελιές πράσινες', [145, 1, 3.8, 15.3], { aliases: ['elies', 'olive'], unit: u('piece', 4) }),
  f('tomato-passata', 'Tomato passata', 'Πασάτα ντομάτας', [32, 1.4, 6, 0.2], { aliases: ['saltsa', 'tomato sauce', 'passata'] }),

  /* ---------------------------------------------------------------- fruit */
  f('banana', 'Banana', 'Μπανάνα', [89, 1.1, 22.8, 0.3], { aliases: ['banana', 'mpanana'], unit: u('piece', 118) }),
  f('apple', 'Apple', 'Μήλο', [52, 0.3, 13.8, 0.2], { aliases: ['milo', 'mylo'], unit: u('piece', 180) }),
  f('orange', 'Orange', 'Πορτοκάλι', [47, 0.9, 11.8, 0.1], { aliases: ['portokali'], unit: u('piece', 150) }),
  f('mandarin', 'Mandarin', 'Μανταρίνι', [53, 0.8, 13.3, 0.3], { aliases: ['mandarini', 'tangerine', 'clementine'], unit: u('piece', 75) }),
  f('pear', 'Pear', 'Αχλάδι', [57, 0.4, 15.2, 0.1], { aliases: ['achladi', 'axladi'], unit: u('piece', 180) }),
  f('peach', 'Peach', 'Ροδάκινο', [39, 0.9, 9.5, 0.3], { aliases: ['rodakino'], unit: u('piece', 150) }),
  f('apricot', 'Apricot', 'Βερίκοκο', [48, 1.4, 11.1, 0.4], { aliases: ['verikoko'], unit: u('piece', 35) }),
  f('kiwi', 'Kiwi', 'Ακτινίδιο', [61, 1.1, 14.7, 0.5], { aliases: ['aktinidio', 'kiwi'], unit: u('piece', 75) }),
  f('grapes', 'Grapes', 'Σταφύλια', [69, 0.7, 18.1, 0.2], { aliases: ['stafylia', 'stafilia'] }),
  f('watermelon', 'Watermelon', 'Καρπούζι', [30, 0.6, 7.6, 0.2], { aliases: ['karpouzi'] }),
  f('melon', 'Melon', 'Πεπόνι', [34, 0.8, 8.2, 0.2], { aliases: ['peponi', 'cantaloupe'] }),
  f('strawberries', 'Strawberries', 'Φράουλες', [32, 0.7, 7.7, 0.3], { aliases: ['fraoules', 'berries'] }),
  f('blueberries', 'Blueberries', 'Μύρτιλα', [57, 0.7, 14.5, 0.3], { aliases: ['myrtila', 'mirtila', 'berries'] }),
  f('raspberries', 'Raspberries', 'Βατόμουρα', [52, 1.2, 11.9, 0.7], { aliases: ['vatomoura', 'berries'] }),
  f('mixed-berries', 'Mixed berries (frozen)', 'Φρούτα του δάσους (κατεψυγμένα)', [50, 0.8, 11.5, 0.3], { aliases: ['berries', 'frouta tou dasous', 'forest fruits'] }),
  f('cherries', 'Cherries', 'Κεράσια', [63, 1.1, 16, 0.2], { aliases: ['kerasia'] }),
  f('figs-fresh', 'Figs, fresh', 'Σύκα φρέσκα', [74, 0.8, 19.2, 0.3], { aliases: ['syka', 'sika', 'fig'], unit: u('piece', 50) }),
  f('figs-dried', 'Figs, dried', 'Σύκα ξερά', [249, 3.3, 63.9, 0.9], { aliases: ['syka', 'sika', 'fig'], unit: u('piece', 20) }),
  f('dates', 'Dates (Medjool)', 'Χουρμάδες', [277, 1.8, 75, 0.2], { aliases: ['xourmades', 'hourmades', 'date'], unit: u('piece', 24) }),
  f('raisins', 'Raisins', 'Σταφίδες', [299, 3.1, 79.2, 0.5], { aliases: ['stafides', 'sultanas'] }),
  f('pomegranate', 'Pomegranate seeds', 'Ρόδι (σπόροι)', [83, 1.7, 18.7, 1.2], { aliases: ['rodi'] }),
  f('mango', 'Mango', 'Μάνγκο', [60, 0.8, 15, 0.4], { aliases: ['mango'] }),
  f('pineapple', 'Pineapple', 'Ανανάς', [50, 0.5, 13.1, 0.1], { aliases: ['ananas'] }),
  f('orange-juice', 'Orange juice (fresh)', 'Χυμός πορτοκάλι (φρέσκος)', [45, 0.7, 10.4, 0.2], { aliases: ['xymos', 'chymos', 'juice', 'oj'] }),
  f('lemon-juice', 'Lemon juice', 'Χυμός λεμονιού', [22, 0.4, 6.9, 0.2], { aliases: ['lemoni', 'lemon'] }),

  /* ---------------------------------------------------------------- nuts, seeds, oils */
  f('almonds', 'Almonds', 'Αμύγδαλα', [579, 21.2, 21.6, 49.9], { aliases: ['amygdala', 'amigdala', 'nuts', 'xiroi karpoi'] }),
  f('walnuts', 'Walnuts', 'Καρύδια', [654, 15.2, 13.7, 65.2], { aliases: ['karydia', 'karidia', 'nuts'] }),
  f('pistachios', 'Pistachios (shelled)', 'Φιστίκια Αιγίνης (καθαρά)', [560, 20.2, 27.2, 45.3], { aliases: ['fistikia', 'aiginis', 'nuts'] }),
  f('cashews', 'Cashews', 'Κάσιους', [553, 18.2, 30.2, 43.9], { aliases: ['kasious', 'nuts'] }),
  f('hazelnuts', 'Hazelnuts', 'Φουντούκια', [628, 15, 16.7, 60.8], { aliases: ['fountoukia', 'nuts'] }),
  f('peanuts', 'Peanuts, roasted', 'Αράπικα φιστίκια', [567, 25.8, 16.1, 49.2], { aliases: ['fistikia', 'arapika', 'nuts'] }),
  f('peanut-butter', 'Peanut butter', 'Φυστικοβούτυρο', [588, 25, 20, 50], { aliases: ['fystikovoutyro', 'fistikovoutiro', 'pb'], unit: u('tbsp', 16) }),
  f('almond-butter', 'Almond butter', 'Βούτυρο αμυγδάλου', [614, 21, 18.8, 55.5], { aliases: ['amygdalovoutyro'], unit: u('tbsp', 16) }),
  f('tahini', 'Tahini', 'Ταχίνι', [595, 17, 21.2, 53.8], { aliases: ['tahini', 'tachini', 'taxini', 'sesame paste'], unit: u('tbsp', 15) }),
  f('sesame', 'Sesame seeds', 'Σουσάμι', [573, 17.7, 23.5, 49.7], { aliases: ['sousami'] }),
  f('chia', 'Chia seeds', 'Σπόροι chia', [486, 16.5, 42.1, 30.7], { aliases: ['chia', 'tsia'], unit: u('tbsp', 12) }),
  f('flaxseed', 'Flaxseed', 'Λιναρόσπορος', [534, 18.3, 28.9, 42.2], { aliases: ['linarosporos', 'linseed'], unit: u('tbsp', 10) }),
  f('sunflower-seeds', 'Sunflower seeds', 'Ηλιόσποροι', [584, 20.8, 20, 51.5], { aliases: ['ilio', 'passatempo'] }),
  f('olive-oil', 'Olive oil', 'Ελαιόλαδο', [884, 0, 0, 100], { aliases: ['elaiolado', 'ladi', 'evoo'], unit: u('tbsp', 13.5) }),
  f('mayonnaise', 'Mayonnaise', 'Μαγιονέζα', [680, 1, 0.6, 75], { aliases: ['magioneza', 'mayo'], unit: u('tbsp', 14) }),

  /* ---------------------------------------------------------------- sweets, snacks, drinks */
  f('honey', 'Honey', 'Μέλι', [304, 0.3, 82.4, 0], { aliases: ['meli'], unit: u('tsp', 7) }),
  f('sugar', 'Sugar', 'Ζάχαρη', [387, 0, 100, 0], { aliases: ['zachari', 'zaxari'], unit: u('tsp', 4) }),
  f('jam', 'Jam', 'Μαρμελάδα', [250, 0.4, 61, 0.1], { aliases: ['marmelada'], unit: u('tbsp', 20) }),
  f('halva', 'Halva (tahini halva)', 'Χαλβάς', [520, 12, 54, 29], { aliases: ['chalvas', 'halvas', 'xalvas', 'halvah'] }),
  f('pasteli', 'Pasteli (sesame and honey bar)', 'Παστέλι', [490, 12, 50, 27], { aliases: ['pasteli'], unit: u('piece', 30) }),
  f('baklava', 'Baklava', 'Μπακλαβάς', [428, 6.7, 37.6, 29], { aliases: ['baklavas', 'mpaklavas'], unit: u('piece', 60) }),
  f('loukoumades', 'Loukoumades (honey doughnuts)', 'Λουκουμάδες', [330, 5, 45, 14.5], { aliases: ['loukoumades', 'donuts'] }),
  f('dark-chocolate', 'Dark chocolate 70%', 'Σοκολάτα υγείας 70%', [598, 7.8, 45.9, 42.6], { aliases: ['sokolata', 'chocolate'] }),
  f('milk-chocolate', 'Milk chocolate', 'Σοκολάτα γάλακτος', [535, 7.7, 59.4, 29.7], { aliases: ['sokolata', 'chocolate'] }),
  f('ice-cream', 'Ice cream, vanilla', 'Παγωτό βανίλια', [207, 3.5, 23.6, 11], { aliases: ['pagoto'] }),
  f('protein-bar', 'Protein bar', 'Μπάρα πρωτεΐνης', [360, 33, 35, 10], { aliases: ['protein bar', 'mpara', 'bar'], unit: u('piece', 60) }),
  f('ketchup', 'Ketchup', 'Κέτσαπ', [112, 1, 26, 0.1], { aliases: ['ketsap'], unit: u('tbsp', 17) }),
  f('beer', 'Beer (lager)', 'Μπίρα', [43, 0.5, 3.6, 0], { aliases: ['mpira', 'bira'] }),
  f('wine', 'Wine, red', 'Κρασί κόκκινο', [85, 0.1, 2.6, 0], { aliases: ['krasi', 'wine'] }),
  f('cola', 'Cola', 'Κόλα', [42, 0, 10.6, 0], { aliases: ['coke', 'soft drink', 'anapsyktiko'] }),
]
